version: '3'

services: 
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: "123456"
        ports: 
            - "5432:5432"
        volumes: 
            - /Users/fkcommunity/Desktop/Postgres/db:/var/lib/postgresql/data